services:
  - type: web
    name: community-info-collector-backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "DEBUG"
      - key: PYTHONUNBUFFERED
        value: "1"